Feat/Add diff. NFT image for each project
GeneralMagicio/abc-launcher pull request #91
Opened 2024-10-16 16:20 UTC by kkatusic

2024-10-16 19:37 UTC, aminlatifi requested changes
@kkatusic Please check if it works after you applied your changes

2024-10-16 19:37 UTC, aminlatifi commented on src/hooks/useNFT.ts
> +      };
Do you know if it worked? 
I was thinking about
```suggestion
      const nftImage = whitelist?.nftImageURI || DEFAULT_BASE_URI;
```

2024-10-16 19:37 UTC, aminlatifi commented on src/components/TokenForm/NFTDeploymentStep.tsx
> +              )}
Instead of repeating code block with only different src field, decide about the `src` in a variable in the above line.

Also, please move the IPFS gateway to a config field.
Moreover, we may don't need to repeat '/ipfs` part if the field fetched from db has it as prefix

2024-10-16 21:57 UTC, kkatusic commented on src/components/TokenForm/NFTDeploymentStep.tsx
> +              )}
Moved to config and left only condition inside src, thx @aminlatifi

2024-10-18 11:58 UTC, aminlatifi reviewed
LGTM, thanks @kkatusic

2024-10-18 11:58 UTC, aminlatifi approved these changes

2024-10-18 11:59 UTC, merged